# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalHackathon' do
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'SwiftyJSON'
    pod 'RealmSwift'
    pod 'SlideMenuControllerSwift'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'ReachabilitySwift', '~> 3' 
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalHackathon

  target 'FinalHackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalHackathonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
